services:
  mysql-db:
    image: mysql:8.0
    container_name: ebank-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: BANK_DB
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${DB_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    image: ebank-backend:${IMAGE_TAG}
    container_name: ebank-backend
    ports:
      - "8080:8080"
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      DB_USERNAME: root
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      APP_CORS_ALLOWED_ORIGIN: ${APP_CORS_ALLOWED_ORIGIN}

  frontend:
    image: ebank-frontend:${IMAGE_TAG}
    container_name: ebank-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  mysql_data: